In [662]:
import numpy as np
import pandas as pd
import plotly.express as px
from matplotlib.colors import ListedColormap
from sklearn.preprocessing import StandardScaler

In [663]:
# Указываем параметры
Z = 3  # Выбираем гипергеометричское распределение
P = 3  # Число признаков
N = 5  # Число классов

M = 100  # Число наблюдений

In [664]:
data = []
for i in range(N):
    count = 10
    ngood = np.random.randint(90, 100)
    nbad = 100 - ngood
    nsample = np.random.randint(1, 100)

    c = np.random.hypergeometric(ngood=ngood, nbad=nbad, nsample=nsample, size=(M, P)) + count
    count += 10
    # ngood - количество "хороших" элементов в выборке
    # nbad - количество "плохих" элементов в выборке
    # nsample - общий размер выборки
    # size - форма матрицы данных, которую

    data.append(c)

In [665]:
# Собираем признаки из всех классов
xs = np.concatenate([c[:, 0] for c in data]) # Признаки по оси X
ys = np.concatenate([c[:, 1] for c in data])  # Признаки по оси Y
zs = np.concatenate([c[:, 2] for c in data]) # Признаки по оси Z

xsyszs = [[xs[i], ys[i], zs[i]] for i in range(len(xs))]  # Собираем тройки признаков

In [666]:
# Создаем список Y, присваивая каждому классу уникальное значение
# Y будет представлять классификационный признак,
# который указывает на принадлежность каждой точки данных к одному из 5 классов.
Y = []
for i in range(N):
    Y.extend([i] * M)

# Преобразуем список Y в массив numpy
Y = np.array(Y)

print(Y)



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [667]:
# Создаем DataFrame `res_df` из списка `xsyszs`, где `xsyszs` содержит тройки признаков (x, y, z) для каждой точки данных.
res_df = pd.DataFrame(xsyszs)

# Создаем трехмерный рассеянный график с использованием библиотеки Plotly Express.
# Аргументы `x=0`, `y=1`, `z=2` указывают столбцы DataFrame для координат осей X, Y и Z соответственно.
# Аргумент `color=Y` определяет цвет точек на графике в соответствии с классификационным признаком из массива `Y`.
fig = px.scatter_3d(res_df, x=0, y=1, z=2, color=Y)

# Отображаем созданный трехмерный график.
fig.show()


In [668]:
from sklearn.preprocessing import MinMaxScaler

# Стандартизируем данные
scaler = MinMaxScaler((0, 1))
scaler.fit(xsyszs)
ss = scaler.transform(xsyszs)
print(type(ss))
print(ss)
# xsys_n = pd.DataFrame(sc.fit_transform(res_df))
# xsys_n.describe()

<class 'numpy.ndarray'>
[[0.01515152 0.01515152 0.01515152]
 [0.         0.         0.        ]
 [0.01515152 0.01515152 0.01515152]
 ...
 [0.13636364 0.13636364 0.16666667]
 [0.13636364 0.09090909 0.15151515]
 [0.13636364 0.13636364 0.15151515]]


In [669]:
# Импортируем класс KMeans из библиотеки scikit-learn для кластеризации данных.
from sklearn.cluster import KMeans

# Создаем объект KMeans с параметрами:
# - n_clusters=5 указывает, что мы хотим разделить данные на 5 кластера.
# - random_state=0 используется для установки начального состояния генератора случайных чисел и обеспечения воспроизводимости результатов.
kmeans = KMeans(n_clusters=5, random_state=0)

# Обучаем модель K-Means на стандартизированных данных `xsys_n`.
kmeans.fit(ss)


/Users/malinatrash/anaconda3/envs/Nerual-Network-Technologies/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=5, random_state=0)

In [670]:
# Создаем DataFrame `df_cluster_centers` для хранения координат центров кластеров.
df_cluster_centers = pd.DataFrame(kmeans.cluster_centers_)

# Выводим DataFrame `df_cluster_centers`, который содержит координаты центров кластеров.
print(df_cluster_centers)

          0         1         2
0  0.972727  0.973030  0.974091
1  0.156508  0.146694  0.150999
2  0.353333  0.348939  0.347424
3  0.020455  0.022121  0.021970
4  0.113907  0.112419  0.115395


In [671]:
# Импортируем функцию confusion_matrix из библиотеки scikit-learn для вычисления матрицы ошибок.
from sklearn.metrics import confusion_matrix

# Выводим матрицу ошибок, которая показывает, как точки данных распределены по кластерам
# и сравнивает это с истинными метками классов.
# `Y` содержит истинные метки классов, а `kmeans.labels_` содержит предсказанные метки кластеров.
confusion_mat = confusion_matrix(Y, kmeans.labels_)
print(confusion_mat)

[[  0   0   0 100   0]
 [100   0   0   0   0]
 [  0   0 100   0   0]
 [  0   0   0   0 100]
 [  0  89   0   0  11]]


In [672]:
import plotly.graph_objects as go

dfff = pd.DataFrame(ss)

fig = go.Figure(data=[
    go.Scatter3d(
        x=dfff[0], y=dfff[1], z=dfff[2], mode='markers', marker=dict(size=2, color=kmeans.labels_)
    ),

    go.Scatter3d(
        x=df_cluster_centers[0],
        y=df_cluster_centers[1],
        z=df_cluster_centers[2],
        mode='markers',
        marker=dict(size=6, color='RED')
    )
])
fig.show()

In [673]:
from sklearn.model_selection import train_test_split

# Разделяем данные на обучающую (70%) и тестирующую (30%) выборки.
X_train, X_test, Y_train, Y_test = train_test_split(ss, Y, test_size=0.4, random_state=123)
print(type(ss))

# X_train - обучающие данные (признаки)
# Y_train - метки классов для обучающих данных
# X_test - тестирующие данные (признаки)
# Y_test - метки классов для тестирующих данных


<class 'numpy.ndarray'>


In [674]:
class Perceptron:
    def __init__(self, learning_rate=0.2, n_iters=600):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.aclivation_func = self._unit_step_func
        self.weights = 3
        self.bias = None

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        y_ = np.array([1 if i > 0 else 0 for i in y])

        for _ in range(self.n_iters):
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = self.aclivation_func(linear_output)
                update = self.lr * (y_[idx] - y_predicted)
                self.weights += update * x_i
                self.bias += update

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        y_predicted = self.aclivation_func(linear_output)
        return y_predicted
    #функция активации (если результат сумматора >= 0, то результат = 1)
    def _unit_step_func(self, x):
        return np.where(x>=0, 1, 0)

In [675]:
#отделяем первый класс от других  в обучающей выборке
y_train1 = [[] for _ in range(len(Y_train))]#создаем массив для отделения из Y_train 1 класса
for _ in range(len(Y_train)):
    if Y_train[_] == 0:
        y_train1[_] = 1
    else:
        y_train1[_] = 0
Y_train1 = np.array(y_train1)
Y_train1 = Y_train1.reshape((len(Y_train),1))

#отделяем первый класс от других  в тестирующей выборке
Y_test1 = [[] for _ in range(len(Y_test))]#создаем массив для отделения из Y_train 1 класса
for _ in range(len(Y_test)):
    if Y_test[_] == 0:
        Y_test1[_] = 1
    else:
        Y_test1[_] = 0
Y_test1 = np.array(Y_test1)
Y_test1 = Y_test1.reshape((len(Y_test),1))


dfff = pd.DataFrame(X_train)

fig = go.Figure(data=[
    go.Scatter3d(
        x=dfff[0], y=dfff[1], z=dfff[2], mode='markers', marker=dict(size=2, color=y_train1)
    )
])
fig.show()


print(len(Y_train1))
print(len(X_train))
print(len(Y_test1))
print(len(X_test))

300
300
200
200


In [676]:
import plotly.graph_objects as go

fig = go.Figure(data=[
    go.Scatter3d(
        x=X_train[0], y=X_train[1], z=X_train[2], mode='markers', marker=dict(size=2, color=y_train1)
    )
])
fig.show()

In [677]:
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Assuming X_train is a 2D array with shape (n_samples, 2)
pr1 = Perceptron(n_iters=1000)

pr1.fit(X_train, y_train1)
pr1train = pr1.predict(X_train)

# fig = plt.figure(figsize=(15, 15))
# ax = fig.add_subplot(111, projection='3d')
# ax.scatter(X_train[:, 0], X_train[:, 1], marker='o', linewidths=1, c=pr1train)

# Define a function for the decision boundary
def f(x, y):
    return (-pr1.bias - pr1.weights[0] * x - pr1.weights[1] * y) / pr1.weights[2]

# Create a meshgrid for plotting the decision boundary
xval = np.linspace(np.min(X_train[:, 0]), np.max(X_train[:, 0]), 100)
yval = np.linspace(np.min(X_train[:, 1]), np.max(X_train[:, 1]), 100)
x, y = np.meshgrid(xval, yval)
z = f(x, y)

# ax.plot_surface(x, y, z, cmap='inferno')
# ax.view_init(0, -50)
# plt.show()

# Confusion matrix
r = confusion_matrix(y_train1, pr1train)
print(r)


[[235   0]
 [  0  65]]
