In [24]:
# ВАРИАНТ 
Z = 5 # Равномерное
F1 = 5 # корень квадратный
F2 = 9 # функция букина

In [25]:
# ПОРЯДОК ВЫПОЛНЕНИЯ ЛАБОРАТОРНОЙ РАБОТЫ

# 1. Сгенерировать случайные числа по указанному закону распределения. Из них создается матрица из M строк (наблюдений) 1 или 2 столбцов (аргументов). Эти числа играют роль аргументов некоторой функциональной зависимости от одного или двух аргументов

# 2. Разделить данные варианта на обучающую и тестирующую выборки

# 3. Осуществить аппроксимацию функций f1 и f2 тремя способами:
# 3.1 С помощью сети прямого распространения сигнала;
# 3.2 С помощью RBF-сети;
# 3.3 С помощью нейро-нечеткой сети ANFIS.

# 4. Построить графики ошибок и сравнения значений функции для обучающей и тестирующей выборки и выходных значений, прогнозированных нейронными сетями. Оценить количественно точность аппроксимации функций.

# 5. Для построения нейро-нечеткой сети ANFIS необходимо выполнить следующие шаги:
# 5.1 По обучающей выборке сгенерировать систему нечеткого вывода и настроить эту систему
# 5.2 Показать структуру построенной системы нечеткого вывода (входные и выходные переменные, функции принадлежности, правила)
# 5.3 Просмотреть поверхность системы нечеткого вывода до и после настройки системы нечеткого вывода с помощью ANFIS
# 5.4 Вычислить выходные значения по системе нечеткого вывода для обучающей и тестирующей выборок.
# 5.5 Построить графики ошибок и сравнения значений функции для обучающей и контролирующей выборки и выходных значений по системе нечеткого вывода до настройки системы и после настройки.

In [26]:
import math
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [27]:
# F1

for num in range(-15, -4):  # Диапазон от -15 до -5
    sqrt_result = math.sqrt(abs(num))
    print(f"Квадратный корень из {num}: {sqrt_result}")

for num in range(-3, 4):  # Диапазон от -3 до 3
    sqrt_result = math.sqrt(abs(num))
    print(f"Квадратный корень из {num}: {sqrt_result}")


Квадратный корень из -15: 3.872983346207417
Квадратный корень из -14: 3.7416573867739413
Квадратный корень из -13: 3.605551275463989
Квадратный корень из -12: 3.4641016151377544
Квадратный корень из -11: 3.3166247903554
Квадратный корень из -10: 3.1622776601683795
Квадратный корень из -9: 3.0
Квадратный корень из -8: 2.8284271247461903
Квадратный корень из -7: 2.6457513110645907
Квадратный корень из -6: 2.449489742783178
Квадратный корень из -5: 2.23606797749979
Квадратный корень из -3: 1.7320508075688772
Квадратный корень из -2: 1.4142135623730951
Квадратный корень из -1: 1.0
Квадратный корень из 0: 0.0
Квадратный корень из 1: 1.0
Квадратный корень из 2: 1.4142135623730951
Квадратный корень из 3: 1.7320508075688772


In [28]:
# F2

def bukin_function(x, y):
    return 100 * math.sqrt(abs(y - 0.01 * x**2)) + 0.01 * abs(x + 10)

# Вычисление значений функции для заданного диапазона x и y
for x_value in range(-15, -4):  # Используем -4, чтобы включить -5
    for y_value in range(-3, 4):  # Используем 4, чтобы включить 3
        result = bukin_function(x_value, y_value)
        print(f"Значение функции в точке ({x_value}, {y_value}): {result}")

Значение функции в точке (-15, -3): 229.178784747792
Значение функции в точке (-15, -2): 206.20528128088304
Значение функции в точке (-15, -1): 180.32756377319947
Значение функции в точке (-15, 0): 150.05
Значение функции в точке (-15, 1): 111.85339887498948
Значение функции в точке (-15, 2): 50.05
Значение функции в точке (-15, 3): 86.65254037844386
Значение функции в точке (-14, -3): 222.7505745132009
Значение функции в точке (-14, -2): 199.037487421324
Значение функции в точке (-14, -1): 172.0865053408525
Значение функции в точке (-14, 0): 140.04
Значение функции в точке (-14, 1): 98.01958971132713
Значение функции в точке (-14, 2): 20.04000000000001
Значение функции в точке (-14, 3): 102.0203902718557
Значение функции в точке (-13, -3): 216.59407827707716
Значение функции в точке (-13, -2): 192.12372712298546
Значение функции в точке (-13, -1): 164.04219466856725
Значение функции в точке (-13, 0): 130.03
Значение функции в точке (-13, 1): 83.09623862918075
Значение функции в точке 

In [29]:
# 1
# Генерация случайных чисел с равномерным распределением
M = 3
uniform_random_numbers = np.random.uniform(0, 10, (M, 2))  # M строк, 2 столбца

# Применение корня квадратного к числам
sqrt_numbers = np.sqrt(uniform_random_numbers)

# Функция Букина (пример)
def bukin_function(x, y):
    return 100 * np.sqrt(np.abs(y - 0.01 * x ** 2)) + 0.01 * np.abs(x + 10)

# Применение функции Букина к числам
bukin_result = bukin_function(uniform_random_numbers[:, 0], uniform_random_numbers[:, 1])

# Создание матрицы аргументов и результатов
arguments_matrix = np.column_stack((uniform_random_numbers, sqrt_numbers))
results_matrix = np.column_stack((uniform_random_numbers, bukin_result))

print("Матрица аргументов (случайные числа и их корни):")
print(arguments_matrix)

print("\nМатрица результатов (аргументы и значения функции Букина):")
print(results_matrix)

Матрица аргументов (случайные числа и их корни):
[[2.81032414 4.93380644 1.67640214 2.22121733]
 [6.5416328  7.91825945 2.55766159 2.8139402 ]
 [0.24311199 7.72741239 0.49306388 2.77982237]]

Матрица результатов (аргументы и значения функции Букина):
[[2.81032414e+00 4.93380644e+00 2.20464828e+02]
 [6.54163280e+00 7.91825945e+00 2.73850086e+02]
 [2.43111992e-01 7.72741239e+00 2.78074037e+02]]


In [30]:
# 2

from sklearn.model_selection import train_test_split

# Предположим, у вас есть матрица данных "arguments_matrix" и матрица результатов "results_matrix"

# Разделение на обучающую (80%) и тестовую (20%) выборки
X_train, X_test, y_train, y_test = train_test_split(arguments_matrix, results_matrix, test_size=0.2, random_state=42)

# X_train - обучающая выборка для аргументов
# X_test - тестовая выборка для аргументов
# y_train - обучающая выборка для результатов
# y_test - тестовая выборка для результатов

# Для использования этих данных в модели вашего выбора (например, линейной регрессии):
from sklearn.linear_model import LinearRegression

# Создание и обучение модели
model = LinearRegression()
model.fit(X_train, y_train)

# Предсказание на тестовой выборке
predictions = model.predict(X_test)

In [31]:
print(X_train.shape)  # Вывод формы обучающих данных
print(X_test.shape)   # Вывод формы тестовых данных

X_train_selected = X_train[:, :2]  # Выбор первых двух значений для обучающих данных
X_test_selected = X_test[:, :2]    # Выбор первых двух значений для тестовых данных



(2, 4)
(1, 4)


In [32]:
# 3.1 

# Создание модели нейронной сети
model = tf.keras.Sequential([
	# Первый скрытый слой с 10 нейронами
    tf.keras.layers.Dense(10, activation='relu'),
    # Выходной слой с одним нейроном (для аппроксимации одномерной функции)
    tf.keras.layers.Dense(1)
])

# Компиляция модели с выбором оптимизатора и функции потерь
model.compile(optimizer='adam', loss='mean_squared_error')

# Обучение модели
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

# Оценка модели на тестовых данных
loss = model.evaluate(X_test, y_test)
print("Потери на тестовых данных:", loss)

# Получение предсказаний модели на тестовых данных
predictions = model.predict(X_test)


Epoch 1/50
1/1 [==============================] - 0s 207ms/step - loss: 26751.9199 - val_loss: 16807.3770
Epoch 2/50
1/1 [==============================] - 0s 14ms/step - loss: 26739.7969 - val_loss: 16800.7969
Epoch 3/50
1/1 [==============================] - 0s 14ms/step - loss: 26727.7031 - val_loss: 16794.2344
Epoch 4/50
1/1 [==============================] - 0s 13ms/step - loss: 26715.6328 - val_loss: 16787.6895
Epoch 5/50
1/1 [==============================] - 0s 14ms/step - loss: 26703.5977 - val_loss: 16781.3945
Epoch 6/50
1/1 [==============================] - 0s 17ms/step - loss: 26691.5898 - val_loss: 16775.4199
Epoch 7/50
1/1 [==============================] - 0s 16ms/step - loss: 26679.6133 - val_loss: 16769.4590
Epoch 8/50
1/1 [==============================] - 0s 17ms/step - loss: 26667.6660 - val_loss: 16763.5137
Epoch 9/50
1/1 [==============================] - 0s 15ms/step - loss: 26655.7461 - val_loss: 16757.5762
Epoch 10/50
1/1 [==============================] - 0s 

In [33]:
import neurokit2 as nk
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Масштабирование данных
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Создание и обучение RBF-сети
n_centers = 10  # Количество центров (кластеров)
rbf_model = nk.GaussianRBF(n_centers=n_centers)
rbf_model.fit(X_train_scaled, y_train, epochs=50)

# Предсказание на тестовых данных
predictions = rbf_model.predict(X_test_scaled)

# Оценка качества модели (например, среднеквадратичная ошибка)
mse = mean_squared_error(y_test, predictions)
print("Среднеквадратичная ошибка:", mse)


ModuleNotFoundError: No module named 'pyrbf'